version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worlds-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - PG_URL=postgres://postgres:postgres@postgres:5432/worlds?sslmode=disable
      - REDIS_URL=redis://redis:6379
    command: ./server start --verbose=5

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: worlds
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data: